apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 7000
      name: mysql
      targetPort: 7000
      nodePort: 30008
    - port: 8080
      name: api
      targetPort: 8080
      nodePort: 30080
  selector:
    app: uaf-api